/* National Council presentation only. Gameplay is supplied by the original inline engine. */
const COUNCIL_ROOMS={home:['Executive council','National briefing','cabinet'],nation:['National administration','Territories and resources','cabinet'],world:['Strategic map','Geography and influence','map'],forces:['Force command','Readiness and procurement','war'],doctrine:['Doctrine council','National strategy','war'],research:['Research directorate','Technology programmes','research'],status:['National assessment','Capabilities and indicators','cabinet'],spy:['Foreign intelligence','Overseas operations','intel'],internal:['Domestic security','Programmes and internal operations','intel'],war:['Defence command','Operational decisions','war'],econ:['Economic council','Budget and infrastructure','finance'],markets:['Commodity markets','Supply and price intelligence','finance'],bourse:['Equity exchange','Indices and sovereign investments','finance'],trade:['Trade council','Contracts and supply chains','trade'],dipl:['Diplomatic corps','Negotiations and agreements','diplomacy'],intel:['Intelligence briefing','Dispatches and after-action reports','intel'],settings:['Campaign archives','Saves, exports and preferences','cabinet']};
const COUNCIL_SHORT={USA:{war:'Department of Defense',spy:'CIA',internal:'Homeland Security',dipl:'Department of State'},RUS:{war:'Ministry of Defence',spy:'SVR',internal:'MVD / FSB',dipl:'Foreign Affairs'},GBR:{spy:'SIS / MI6',internal:'Home Office'},CHN:{spy:'MSS'},IND:{spy:'R&AW'},FRA:{spy:'DGSE'},DEU:{spy:'BND'},ISR:{spy:'Mossad'},PAK:{spy:'ISI'},UKR:{spy:'HUR'},AUS:{spy:'ASIS'},CAN:{spy:'CSIS'},JPN:{spy:'PSIA'},KOR:{spy:'NIS'},TUR:{spy:'MİT'}};
// User-requested naming is presentation data only, never a change to game rules.
DEPTS.USA[DEPT_WAR]='Department of Defense';
function councilInstitution(key,id=G?.player||chosen){const country=DATA.find(d=>d.id===id);const name=country?.name||id;if(['war','forces','doctrine'].includes(key))return dept(id,DEPT_WAR);if(key==='spy')return dept(id,DEPT_INTEL)+(id==='RUS'?' (SVR)':'');if(key==='internal')return dept(id,DEPT_INTERIOR)+(id==='RUS'?' · Federal Security Service (FSB)':'');if(['econ','bourse','markets'].includes(key))return dept(id,DEPT_FINANCE);if(key==='dipl')return dept(id,DEPT_FOREIGN);if(key==='research')return dept2(id,DEPT_SCIENCE);if(key==='trade')return dept2(id,DEPT_TRADE);return name+' · '+COUNCIL_ROOMS[key][0];}
function councilArt(id,cls=''){const a=NATIONAL_ART[id];if(!a)return '<div class="national-portrait '+cls+'"><div class="portrait-unavailable">'+esc(DATA.find(d=>d.id===id)?.name||id)+'</div></div>';return '<div class="national-portrait '+cls+'" style="--atlas-ratio:'+(a.width/5/(a.height/2))+'" role="img" aria-label="Fictional '+esc(DATA.find(d=>d.id===id)?.name||id)+' council adviser"><div class="atlas-window"><img src="'+a.src+'" alt="" style="left:-'+a.col*100+'%;top:-'+a.row*100+'%" decoding="async"></div></div>';}
const councilStage=document.createElement('section');councilStage.id='council-stage';document.querySelector('#cols').prepend(councilStage);
let councilPrev='',councilReturnFocus=null,councilMotion=true,councilCompact=false;
try{councilMotion=localStorage.getItem('council-motion')!=='off';councilCompact=localStorage.getItem('council-compact')==='true'}catch(e){}
function councilPrefs(){document.body.classList.toggle('motion-paused',!councilMotion);document.body.classList.toggle('compact-council',councilCompact)}councilPrefs();
function councilAdvice(key){if(!G)return 'Select your nation and configure the campaign.';const n=ME(),wars=enemiesOf(G.player),net=netRes(G.player);if(['trade','markets'].includes(key)){const sh=RES.filter(r=>net[r.k]<-.3).map(r=>r.n.toLowerCase());return sh.length?'Reserves are declining in '+sh.join(', ')+'. Review supply before committing to new orders.':'Current resource flows are balanced. Review the price and terms of each agreement.'}if(['war','forces'].includes(key))return (wars.length?'Active opponents: '+wars.map(id=>N(id).name).join(', ')+'. ':'No active fronts. ')+'Army status: '+statusWord(status(n.army)).toLowerCase()+'. '+n.ops+' operations remain.';if(key==='dipl')return G.offers.length?G.offers.length+' proposals await your response. Examine each offer before deciding.':'No incoming proposals. Select a nation to open negotiations.';if(key==='econ')return 'Treasury '+money(n.money)+'. Monthly balance '+(income(G.player)>=0?'+':'')+money(income(G.player))+'.';if(key==='spy')return 'Review network strength, mission cost, success chance and exposure before authorising an operation.';if(key==='internal')return 'Public scrutiny is '+Math.round(n.secHeat||0)+'. Security programmes affect upkeep and public approval.';if(key==='bourse')return 'Sovereign fund value: '+money(fundValue(G.player))+'. Market moves affect both investments and the economy.';return 'National stability '+Math.round(n.stab)+'/100. '+G.offers.length+' proposals and '+wars.length+' active fronts.';}
function councilNavigate(key){if(!G||!COUNCIL_ROOMS[key])return;closeSheet();TAB=key;if(key==='intel')G.unread=0;render();document.querySelector('#view').scrollTop=0;document.querySelector('#cols').scrollTop=0;}
function councilBuildStage(key){const r=COUNCIL_ROOMS[key],n=ME();councilStage.dataset.room=r[2];councilStage.innerHTML=councilArt(G.player)+'<div class="stage-shade"></div><div class="stage-top"><span class="eyebrow">'+n.flag+' '+esc(n.name)+'</span><div class="room-marker">'+esc(r[0])+'</div></div><div class="stage-bottom"><span class="eyebrow">Council liaison</span><h2>'+esc(councilInstitution(key))+'</h2><p>'+esc(councilAdvice(key))+'</p><div class="scene-shortcuts"><button data-council-go="nation">National priorities</button><button data-council-go="dipl">Review proposals <b>'+G.offers.length+'</b></button></div><div class="scene-caption">'+dateOf(G.turn)+' · FICTIONAL COUNCIL SCENE</div></div>';councilStage.querySelectorAll('[data-council-go]').forEach(b=>b.onclick=()=>councilNavigate(b.dataset.councilGo));}
function councilUpdate(){if(!G||HEADLESS)return;const key=COUNCIL_ROOMS[TAB]?TAB:'home';councilBuildStage(key);document.body.dataset.councilNation=G.player;document.body.dataset.councilRoom=key;document.querySelectorAll('[data-tab]').forEach(b=>{const k=b.dataset.tab;if(!COUNCIL_ROOMS[k])return;const original=TABS.find(t=>t.k===k).t;const label=COUNCIL_SHORT[G.player]?.[k];const t=b.querySelector('.t');if(label&&t){const badge=t.querySelector('.badge')?.outerHTML||'';t.innerHTML=esc(label)+badge}b.title=original+' · '+councilInstitution(k);b.setAttribute('aria-label',original+' · '+councilInstitution(k));b.setAttribute('aria-current',k===key?'page':'false')});const inner=document.querySelector('#view .inner');if(inner){const h=document.createElement('header');h.className='council-heading';h.innerHTML='<div><span class="eyebrow">'+esc(COUNCIL_ROOMS[key][1])+'</span><h1>'+esc(councilInstitution(key))+'</h1></div><button type="button" class="help-command" id="all-commands">All departments</button>';inner.prepend(h);h.querySelector('button').onclick=councilCommands;if(councilPrev!==key){inner.classList.remove('arrive');void inner.offsetWidth;inner.classList.add('arrive');councilPrev=key}}
let railTools=document.querySelector('#council-tools');if(!railTools){railTools=document.createElement('div');railTools.id='council-tools';document.querySelector('#turnbar').prepend(railTools)}railTools.innerHTML='<button id="council-board">World board</button><button id="council-dispatches">Dispatches</button><button id="council-prefs" aria-label="Presentation settings">View</button>';railTools.querySelector('#council-board').onclick=()=>councilPanel('board');railTools.querySelector('#council-dispatches').onclick=()=>councilPanel('dispatches');railTools.querySelector('#council-prefs').onclick=councilDisplay;if(key==='settings')councilExportCard();councilSceneHeaders(key);}
function councilEnvironment(key){const type=COUNCIL_ROOMS[key]?.[2]||'cabinet';const cells={war:0,diplomacy:1,trade:2,intel:3,research:4,finance:5,cabinet:5,map:0};const i=cells[type]??5;return '<div class="department-scene" aria-hidden="true"><div class="environment-window"><img src="assets/departments.png" alt="" style="left:-'+(i%3)*100+'%;top:-'+Math.floor(i/3)*100+'%"></div></div>';}
function councilSceneHeaders(key){const h=document.querySelector('.council-heading');if(h&&!h.querySelector('.department-scene'))h.insertAdjacentHTML('afterbegin',councilEnvironment(key));}
const councilOriginalRender=render;render=function(){councilOriginalRender();if(G&&!HEADLESS)councilUpdate()};
function councilCommands(){openSheet('All departments','<div class="department-grid">'+TABS.map(t=>'<button class="department-option" data-council-go="'+t.k+'"><strong>'+esc(t.t)+'</strong><span>'+esc(councilInstitution(t.k))+'</span></button>').join('')+'</div>');document.querySelectorAll('#sheet-body [data-council-go]').forEach(b=>b.onclick=()=>councilNavigate(b.dataset.councilGo));}
function councilPanel(type){openSheet(type==='board'?'World board':'Dispatches',type==='board'?boardList():rightPanel());document.querySelectorAll('#sheet-body [data-nat]').forEach(b=>b.onclick=()=>natSheet(b.dataset.nat));document.querySelectorAll('#sheet-body [data-act="brief"]').forEach(b=>b.onclick=openBriefing);}
function councilDisplay(){openSheet('Presentation','<label class="council-check"><input id="council-motion" type="checkbox" '+(councilMotion?'checked':'')+'> Ambient motion</label><label class="council-check"><input id="council-compact" type="checkbox" '+(councilCompact?'checked':'')+'> Compact artwork for more decision space</label><p class="hint">Your gameplay settings are unchanged.</p><div class="edition-links"><a href="desktop.html">Desktop edition</a><a href="mobile.html">Mobile edition</a></div>');document.querySelector('#council-motion').onchange=e=>{councilMotion=e.target.checked;councilPrefs();try{localStorage.setItem('council-motion',councilMotion?'on':'off')}catch(e){}};document.querySelector('#council-compact').onchange=e=>{councilCompact=e.target.checked;councilPrefs();try{localStorage.setItem('council-compact',String(councilCompact))}catch(e){}};}
function councilExportCard(){const card=document.createElement('section');card.className='card export-card';card.innerHTML='<div class="card-h"><h3>Game source and editions</h3></div><p>Export your campaign with the original controls below. Download the complete project separately to edit or host it.</p><a class="btn" download href="downloads/brinkmanship-code.zip">Download interface and code</a> <a class="btn" download href="downloads/brinkmanship-artwork.zip">Download country artwork</a><p class="hint">Extract both ZIPs into the same folder for the complete GitHub project.</p><div class="edition-links"><a href="desktop.html">Desktop edition</a><a href="mobile.html">Mobile edition</a><a href="README.md">Project guide</a></div><p class="hint">Save files stay on this device. Export a campaign before switching devices or origins.</p>';document.querySelector('#view .inner').insertBefore(card,document.querySelector('#view .inner').children[1]);}
const councilOriginalOpen=openSheet,councilOriginalClose=closeSheet;
openSheet=function(title,html){if(!document.querySelector('#sheet').classList.contains('on'))councilReturnFocus=document.activeElement;councilOriginalOpen(title,html);const s=document.querySelector('#sheet');s.setAttribute('role','dialog');s.setAttribute('aria-modal','true');s.setAttribute('aria-labelledby','sheet-title');let art=document.querySelector('#council-decision-art');if(!art){art=document.createElement('aside');art.id='council-decision-art';s.prepend(art)}const key=COUNCIL_ROOMS[TAB]?TAB:'home';art.innerHTML=councilArt(G?.player||chosen)+'<div class="stage-shade"></div><div class="decision-caption"><span class="eyebrow">'+(G?ME().flag+' '+esc(ME().name):'National council')+'</span><h2>'+esc(councilInstitution(key))+'</h2><p>Awaiting your decision</p></div>';const head=document.querySelector('#sheet-head');head.querySelector('.department-scene')?.remove();head.insertAdjacentHTML('afterbegin',councilEnvironment(key));document.querySelector('#sheet-x').focus();};
closeSheet=function(){councilOriginalClose();if(councilReturnFocus?.isConnected)councilReturnFocus.focus()};window.closeSheet=closeSheet;document.querySelector('#sheet-x').onclick=closeSheet;document.querySelector('#scrim').onclick=closeSheet;
document.addEventListener('keydown',e=>{const s=document.querySelector('#sheet');if(!s.classList.contains('on'))return;if(e.key==='Escape'){e.preventDefault();closeSheet()}if(e.key==='Tab'){const f=[...s.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')].filter(x=>x.getClientRects().length);if(!f.length)return;if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()}}});
function councilPicks(){const n=DATA.find(d=>d.id===chosen);let art=document.querySelector('#council-selection');if(!art){art=document.createElement('div');art.id='council-selection';document.querySelector('#pickinfo').before(art)}art.innerHTML=councilArt(chosen)+'<div class="selection-caption"><span class="eyebrow">'+n.flag+' National council</span><h2>'+esc(n.name)+'</h2><p>'+esc(dept(chosen,DEPT_INTEL))+'</p></div>';document.querySelector('#setup .tagline').textContent=DATA.length+' nations. Take your seat, hear the council, and decide the course of your campaign.';}
const councilOriginalPicks=renderPicks;renderPicks=function(){councilOriginalPicks();councilPicks()};renderPicks();document.querySelector('#startbtn').textContent='Take your seat';document.querySelector('#setup').insertAdjacentHTML('afterbegin','<div class="setup-mast"><span class="eyebrow">NATIONAL COUNCIL EDITION</span><div class="edition-links"><a href="desktop.html">Desktop</a><a href="mobile.html">Mobile</a></div></div>');
// Offline shell is opt-in through browser installation; no server or account needed.
if('serviceWorker' in navigator&&location.protocol!=='file:'&&!location.protocol.startsWith('capacitor'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
